version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./www:/var/www
    environment:
      - HOST_IP=${HOST_IP}

  gunicorn:
    build:
      context: .   
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    volumes:
      - ./www:/var/www
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    depends_on:
      - app
    environment:
      - HOST_IP=${HOST_IP}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    depends_on:
      - gunicorn
