version: '3.8'

services:
  ubuntu-desktop:
    image: kasmweb/ubuntu-jammy-desktop:1.14.0
    shm_size: 512m
    ports:
      - "6903:6901"
    environment:
      - VNC_PW=1234
    restart: on-failure
    volumes:
      - ./file_transfer/a_2024-02-21_12-16-04-329907/Tu_aventura_a_Marruecos_te_esta_esperando_.eml:/home/ubuntu/eml_file.eml
