version: '3.8'

services:
  ubuntu-desktop:
    image: kasmweb/ubuntu-jammy-desktop:1.14.0
    shm_size: 512m
    ports:
      - "6902:6901"
    environment:
      - VNC_PW=1234
    restart: on-failure
