version: '3.8'

services:
  kasm-firefox:
    image: kasmweb/kali-rolling-desktop:1.14.0
    shm_size: 512m
    ports:
      - "6902:6901"
    environment:
      - VNC_PW=1234
    restart: on-failure
